homework3
StrategDZR/mera_java_se pull request #2
Opened 2020-10-19 13:26 UTC by StrategDZR

add homework3 tasks to master

2020-10-19 17:23 UTC, VeryBadProgrammer requested changes

2020-10-19 17:23 UTC, VeryBadProgrammer commented on homework3/Person.java
> +        int rndIndex = rnd.nextInt(arr.length - 1);
Последний элемент в массиве никогда не выпадет?

2020-10-19 17:23 UTC, VeryBadProgrammer commented on homework3/SequentialRandom.java
> +        if (prevValue == 0) {
Что,если тебе в рандоме попадется ноль?

2020-10-19 17:23 UTC, VeryBadProgrammer commented on homework3/SequentialRandom.java
> +            prevValue = getValue();
Ты передаешь значение value здесь, но нигде не используешь(кроме проверки на ноль) Значит можно передавать любые значения?

2020-10-20 05:37 UTC, StrategDZR commented on homework3/Person.java
> +        int rndIndex = rnd.nextInt(arr.length - 1);
Неправильно баунд задал, да.
Починено.

2020-10-20 05:38 UTC, StrategDZR commented on homework3/SequentialRandom.java
> +        if (prevValue == 0) {
Добавил проверку на ноль и перезапуск рандомайзера в случае, если выпадет ноль.

2020-10-20 05:40 UTC, StrategDZR commented on homework3/SequentialRandom.java
> +            prevValue = getValue();
По большому счёту, да, можно просто писать туда "1", если не первый инстанс объекта был создан.
Текущая реализация основана на подсказке в задании:
`Подсказка: Используйте статическую переменную в классе, чтобы хранить значение предыдущего объекта.`

2020-10-20 15:56 UTC, VeryBadProgrammer requested changes

2020-10-20 15:56 UTC, VeryBadProgrammer commented on homework3/SequentialRandom.java
> +            resetRandom();
Ненужная рекурсия не очень хорошая идея.
Все упирается в то, зачем тебе переменная prevValue, если хранить предыдущее значение,как сказано в подсказке, то это можно сделать более эфеективным кодом, с меньшим количеством условий
Если же ты просто используешь эту переменную как проверку,то эффективнее будет использовать boolen переменную, которая будет проверять ресетил ли рандом или нет

2020-10-20 17:34 UTC, StrategDZR commented on homework3/SequentialRandom.java
> +            resetRandom();
Заменил на булеан, в итоге проверка на ноль в "resetRandom()" оказалась избыточной

2020-10-21 11:48 UTC, VeryBadProgrammer commented on homework3/SequentialRandom.java
> +    private static int value = 0;
Можно не инициализировать, так как он все равно перетрется в любом случае

2020-10-21 13:35 UTC, StrategDZR commented on homework3/SequentialRandom.java
> +    private static int value = 0;
исправлено

2020-10-21 17:12 UTC, VeryBadProgrammer approved these changes

2020-10-21 20:28 UTC, merged