homework4
StrategDZR/mera_java_se pull request #4
Opened 2020-10-20 16:10 UTC by StrategDZR

add homework4

2020-10-22 18:15 UTC, VeryBadProgrammer requested changes

2020-10-22 18:15 UTC, VeryBadProgrammer commented on homework4/lesson4task2/Main.java
> +
можешь вывести на экран какие фабрики у тебя в массиве arrayOfFabricsWithRandomType?
и вывести фабрики+ фрукты после создания массива arrayOfFruitsFromAllFabrics

2020-10-23 06:38 UTC, StrategDZR commented on homework4/lesson4task2/Main.java
> +
Добавил.
Пример вывода:
```
[lesson4task2.LongPineapplesFactory@4554617c, lesson4task2.LongPineapplesFactory@4554617c, lesson4task2.LongPineapplesFactory@4554617c, lesson4task2.LongPineapplesFactory@4554617c, lesson4task2.LongPineapplesFactory@4554617c, lesson4task2.LongPineapplesFactory@4554617c, lesson4task2.LongPineapplesFactory@4554617c, lesson4task2.LongPineapplesFactory@4554617c, lesson4task2.LongPineapplesFactory@4554617c, lesson4task2.LongPineapplesFactory@4554617c]
Type of fruit: Pineapple; Height of tail: 403171876; Weight:81
Type of fruit: Pineapple; Height of tail: 132762207; Weight:94
Type of fruit: Apple; Color: Green; Weight: 56
Type of fruit: Apple; Color: Green; Weight: 36
Type of fruit: Apple; Color: Green; Weight: 20
Type of fruit: Apple; Color: Green; Weight: 55
Type of fruit: Apple; Color: Red; Weight: 87
Type of fruit: Apple; Color: Red; Weight: 5
Type of fruit: Apple; Color: Green; Weight: 68
Type of fruit: Apple; Color: Green; Weight: 81
Type of fruit: Pineapple; Height of tail: 226656426; Weight:34
Type of fruit: Pineapple; Height of tail: 691274255; Weight:50
Type of fruit: Apple; Color: Green; Weight: 88
Type of fruit: Apple; Color: Green; Weight: 18
Type of fruit: Apple; Color: Green; Weight: 39
Type of fruit: Apple; Color: Green; Weight: 36
Type of fruit: Orange; Thickness: 4; Weight: 32
Type of fruit: Orange; Thickness: 2; Weight: 69
Type of fruit: Apple; Color: Green; Weight: 57
Type of fruit: Apple; Color: Green; Weight: 96

Process finished with exit code 0
```

Вопрос с тем, что нужно показывать в массиве arrayOfFabricsWithRandomType остается открытым, из задания не ясно.

2020-10-23 08:36 UTC, VeryBadProgrammer commented on homework4/lesson4task2/Main.java
> +
А, так тебе в массив типа fruit надо добавить элементы из массва arrayOfFabricsWithRandomType
Тогда и выводить только фрукты нужно

2020-10-24 09:43 UTC, VeryBadProgrammer approved these changes

2020-10-24 18:37 UTC, merged