Homework5
StrategDZR/mera_java_se pull request #5
Opened 2020-10-23 06:30 UTC by StrategDZR

add homework5

2020-10-24 08:20 UTC, VeryBadProgrammer commented on homework5/homework5/task2/Games.java
> +    static Games getGameForASeason(Season s) {
Вот этот метод лучше перекинуть в Season, так как фактически игра без сезона может существовать, но условие накладывается на моменте сезона
То есть нет смысла создавать поедание ягод зимой, а потом уже это проверять, лучше сначала проверить и создавать возможные варианты

2020-10-24 08:23 UTC, VeryBadProgrammer commented on homework5/homework5/task2/Games.java
> +    MEASURING_PUDDLES_BY_BOOTS;
Также попробуй вывести название игр не капсом или на русском(не меняя название переменной)
Так как предложение у тебя отображается: 'Y персоны с именем Don любимая игра - MEASURING_PUDDLES_BY_BOOTS' С доном все понятно, а попробуй что-нибудь придумать, чтобы название игры по русски

2020-10-24 08:24 UTC, VeryBadProgrammer requested changes

2020-10-24 08:24 UTC, VeryBadProgrammer commented on homework5/homework5/task2/Person.java
> +        return "Y персоны с именем " + getName()
Что такое Y?)

2020-10-25 11:20 UTC, StrategDZR commented on homework5/homework5/task2/Person.java
> +        return "Y персоны с именем " + getName()
Опечатка, починил

2020-10-25 11:21 UTC, StrategDZR commented on homework5/homework5/task2/Games.java
> +    MEASURING_PUDDLES_BY_BOOTS;
Обновил getGameForASeason(), чтобы выводилась строка с названием игры вместо значения из enum

2020-10-25 11:24 UTC, StrategDZR commented on homework5/homework5/task2/Games.java
> +    static Games getGameForASeason(Season s) {
Перенёс

2020-10-25 11:44 UTC, VeryBadProgrammer commented on homework5/homework5/task2/Games.java
> +    MEASURING_PUDDLES_BY_BOOTS;
есть способ значительно проще, вот тут есть инфа подробнее https://beginnersbook.com/2014/09/java-enum-examples/
раздел: Enum Fields and Methods
он лучше подходит, так как название будет одинаково для любого вызова поля игры, а в случае,который сейчас, если я просто захочу вынести название игры, то мне придется его самой задать и я могу сделать опечатку где нибудь или вообще не то вставить

2020-10-26 11:22 UTC, StrategDZR commented on homework5/homework5/task2/Games.java
> +    MEASURING_PUDDLES_BY_BOOTS;
Да, так гораздо интереснее. Такой же подход был и в лекции, но я его оставил как запасной, если switch не подойдет.

2020-10-27 17:21 UTC, VeryBadProgrammer approved these changes

2020-10-28 11:44 UTC, merged