Homework6
StrategDZR/mera_java_se pull request #6
Opened 2020-10-28 11:44 UTC by StrategDZR

Add sulotion for homework 6

2020-10-28 18:20 UTC, VeryBadProgrammer requested changes

2020-10-28 18:20 UTC, VeryBadProgrammer commented on homework6/homework6/task1/MyArrayList.java
> +    void add(T t) {
обычно имя пишут не t, а какое нибудь понятное,вроде:
void add(T element)

2020-10-28 18:20 UTC, VeryBadProgrammer commented on homework6/homework6/task1/MyArrayList.java
> +                flag = true;
можно оптимизировать эту запись без флага, тут вызвав return

2020-10-28 19:06 UTC, StrategDZR commented on homework6/homework6/task1/MyArrayList.java
> +    void add(T t) {
Переименовал t в item.

2020-10-28 19:08 UTC, StrategDZR commented on homework6/homework6/task1/MyArrayList.java
> +                flag = true;
Флаг убрал.

2020-10-29 15:26 UTC, VeryBadProgrammer commented on homework6/homework6/task1/MyArrayList.java
> +    T get(int i) {
тут лучше тоже переименовать i  в индекс

2020-10-29 16:00 UTC, StrategDZR commented on homework6/homework6/task1/MyArrayList.java
> +    T get(int i) {
Однобуквенные имена переменных только в циклах, остальное должно быть более-менее осмысленно?

2020-10-29 16:11 UTC, VeryBadProgrammer commented on homework6/homework6/task1/MyArrayList.java
> +    T get(int i) {
ага

2020-10-29 16:11 UTC, VeryBadProgrammer approved these changes

2020-10-29 16:16 UTC, merged